version: '3.9'
services:
  backend:
    container_name: node-backend
    build: "."
    ports:
      - "4041:4040"
    depends_on:
      - db
    networks:
      - node-ts
  
  db:
    image: mysql
    container_name: databasemysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=prodigi
      - MYSQL_DATABASE=prodigi
      - MYSQL_USER=prodigi
      - MYSQL_PASSWORD=prodigi
    volumes:
      - dbsql:/var/lib/mysql
    networks:
      - node-ts

volumes:
  dbsql:

networks:
  node-ts:
    driver: bridge
